name: gps_advanced_students
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  bitsdojo_window: ^0.1.6
  cloud_firestore: ^5.5.0
  connectivity_plus: ^6.1.0
  delightful_toast: ^1.1.0
  dyn_mouse_scroll: ^1.0.7
  equatable: 2.0.7
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_heatmap_calendar: ^1.0.5
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  gap: ^3.0.1
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  iconsax_plus: ^1.0.0
  meta: ^1.15.0
  shared_preferences: ^2.3.3
  supabase_flutter: ^2.8.0
  window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/onboarding/
